spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pareto?currentSchema=core
    username: pareto
    password: pareto
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: core
